### ISSUE TITLE
This needs to support composer/installers version 2

### ISSUE THREAD

**Issue by kmajzlik** [zodiacmedia/drupal-libraries-installer#4]

**Comment by kmajzlik** [comment]
See https://github.com/zodiacmedia/drupal-libraries-installer/pull/5

**Comment by laurisigaunis** [comment]
Would love to see this released asap

**Comment by codebymikey** [comment]
Thanks for the PR @kmajzlik, this issue has been closed by #5 and published in the 1.5.0 release.
